name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  chopper: 8.2.0
  collection: 1.19.1
  http: 1.3.0
  json_annotation: 4.9.0

dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  chopper_generator: ^8.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.10.0
  lints: 5.1.1
